### ISSUE TITLE
Crops won't grow indoors

### ISSUE THREAD

**Issue by FlyingGMM** [Pwn9/PwnPlantGrowth#14]
Hi, I admin on a 1.16.5 factions-political RP server. We installed this plugin to improve specialization and arable land scarcity, and for that purpose it's worked great. However, indoor farms, particularly automatic farms such as for pumpkins and sugarcane, don't work at all. I have tried the following:
-Turning UV light off
-Turning UV light on, and listing every light-giving block as providing UV light
-Setting pumpkins/pumpkin stems under `grow_in_dark`

None of this works; the crops don't grow whatsoever. This is very disruptive for our server, because much of the economy is based on producing pumpkins and selling them to villagers for emeralds. What should we do to resolve this?

Thank you.

**Comment by msudol** [comment]
set natural light level to 0 from default of 10.  This setting stops crops from growing underground or from unnatural light

- Natural sky light level: 0 allows any, 10 is sunlight through glass/tree leaves, 15 is direct sunlight
- min_natural_light: 10

**Comment by FlyingGMM** [comment]
We considered doing that, but wouldn't that also make crops grow at night?

**Comment by msudol** [comment]
> 
> 
> We considered doing that, but wouldn't that also make crops grow at night?

Crops will grow if there any appropriate level of light (that's built into minecraft - not part of the plugin)..  so, if they are indoors or underground and you have the appropriate amount of artificial light (torches, goldstone, etc) the crops will grow all the time, even without this plugin.

**Comment by FlyingGMM** [comment]
Right, but if there are crops in a field they're not lit, won't they normally not grow by default at night? And then setting the plants to grow in any light would then let them grow regardless?
