### ISSUE TITLE
Minor Change

### ISSUE THREAD

**Issue by KentBrought** [Pwn9/PwnPlantGrowth#19]
For PwnPlantGrowth, I think it would be cool to see if remove the ability to place the crops. This seems like it wouldn't be very difficult of a change to add, and it would make this plugin compatible with a lot of other plugins. I love the concept of this plugin so far! Keep it up! @msudol @ptoal

**Comment by msudol** [comment]
I feel like this would be a different plugin entirely... based on the event that would be watched for..  PwnPlantGrowth watches for methods of plant growing whereas to prevent planting a crop would be looking at the onPlayerInteract events.  I'll keep it in mind but don't think I'd make it part of this plugin.
