### ISSUE TITLE
Suggestion - display crop growth time when player left clicks seeds in biome.

### ISSUE THREAD

**Issue by Kwikxilver** [Pwn9/PwnPlantGrowth#8]
While this mod works well, one suggestion to make it a bit more user friendly is for players to get a message when they left click seeds on the ground in the biome.

That way, players can be in the know before they waste precious seeds by knowing whether the crop will grow or not and making the decision based on that.

Not a high priority, but would be a great QoL improvement if you are interested.

**Comment by msudol** [comment]
Release 2.5.6 adds a beta version of this feature, tested and working on most growable item types.
