### ISSUE TITLE
Bonemeal on grass doesn't generate anything, even when enabled in config.

### ISSUE THREAD

**Issue by Kwikxilver** [Pwn9/PwnPlantGrowth#9]
Hello again!

Found a bug, I'm not really sure what's going wrong here. Using bonemeal on grass produces the "green spark" particle effect, but doesn't actually generate any tallgrass, flowers etc - anything. This happens in every biome from what I can see. The "green spark" effect is also sunken into the ground, weirdly.

When I delete my config and generate a new one, the issue is gone. When I swapped my config back in, the issue reappeared. I copied in the "GRASS" section from the newly generated config into my own config, reloaded and the issue was still there so not really sure what's going on.

My config: [https://pastebin.com/VrhQn8Un](https://pastebin.com/VrhQn8Un)

My BlockGrow.log: [https://pastebin.com/9F05ByVv](https://pastebin.com/9F05ByVv)

Let me know if you need any more info, but I think this is a bug. Thanks for your work!

**Comment by msudol** [comment]
I'm going to re-work bonemeal altogether at some point.. it's glitchy but there is a new method in spigot to handle the event.

**Comment by msudol** [comment]
Should be resolved for now in latest release 2.5.7
